GET http://127.0.0.1:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test title",
  "author": "Me",
  "url": "whatisthisurl",
  "likes": 23,
  "user": "6a82b6b7d6231efb8efcce34"
}